#!/bin/sh

function checkFile() {
    inc=$1
    filename="/data/out/tcp-stunnel"
    ext=".pcap"

    if [ -z ${inc} ]
    then
        if ! [ -f ${filename}${ext} ]
        then
            outfile=${filename}${ext}
            touch ${outfile}
            echo "[tcpdump] Defined .pcap file as ${outfile}"
        else
            checkFile 1
        fi
    else
        if ! [ -f ${filename}-${inc}${ext} ]
        then
            outfile=${filename}-${inc}${ext}
            touch ${outfile}
            echo "[tcpdump] Defined .pcap file as ${outfile}"
        else
            checkFile $((inc+1))
        fi
    fi
}

if [ -z ${outfile} ]
then
    echo "[tcpdump] Allocating .pcap file"
    checkFile
fi

echo "[tcpdump] Starting tcpdump:"
echo "[tcpdump]     tcpdump -i eth0 -vvv -w ${outfile}"
tcpdump -i eth0 -vvv -w ${outfile}
